openapi: 3.0.0

info:
  title: Simple API
  version: "1.0.0"

servers:
  - url: http://localhost:5000/v1

paths:
  /test:
    get:
      summary: simple test.
      description: test nested objects as query parameter.
      operationId: app.get_test
      responses:
        200:
          description: variables context
          content:
            application/json:
              examples:
                default:
                  summary: variables context
                  value: | 
                    {
                      "context": {
                        "localeCode": "en",
                        "languageCode": "en",
                        "portfolio": "all"
                      }
                    }
        400:
          description: error
          content:
            application/json:
              examples:
                default:
                  summary: error
                  value: | 
                    {
                      "reason": "foo"
                    }    
      parameters:
        - name: variables
          in: query
          description: filter parameter.
          required: true
          explode: false
          schema: 
            type: object
            required:
              - context
            properties:
              context:
                title: Context
                type: object
                required:
                  - localeCode
                  - languageCode
                  - portfolio
                properties:
                  localeCode:
                    title: localeCode
                    type: string
                    enum: [en, uk]
                  languageCode:
                    title: languageCode
                    type: string
                    enum: [en,uk]
                  portfolio:
                    title: portfolio
                    type: string
                    enum: [all, first]
                